version: '3.5'

services:
  db:
    container_name: db_auth
    ports:
      - '${POSTGRES_EXTERNAL_PORT:-54332}:5432'
    restart: always
    environment:
      - 'POSTGRES_DB=${DB_DATABASE}'
      - 'POSTGRES_USER=${DB_USERNAME}'
      - 'POSTGRES_PASSWORD=${DB_PASSWORD}'
    image: postgres:14.3-alpine
  