stages:
  - deploy
deploy_production:
  stage: deploy
  script:
  - rsync -av * /var/www/rtmcuz/
  - cd /var/www/rtmcuz/
  - service rtmc stop
  - dotnet publish -c Release ./ --output /var/www//publish/rtmcuz
  - service rtmc start
  environment:
    name: production
    url: https://rtmc.uz/
  only:
  - master
