stages:
  - deploy
deploy_production:
  stage: deploy
  script:
  - rsync -av * /var/www/rtmcuz/ --no-perms --no-owner --no-group
  - cd /var/www/rtmcuz/
  environment:
    name: production
    url: https://rtmc.uz/
  only:
  - master
